name: LabBuilder - Bicep ARM Build

on: 
    pull_request: 
      paths:
        - '**.bicep'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    BicepBuildandLint:
        name: "Bicep Build and Lint"
        runs-on: ubuntu-latest
    
        steps:
            # Checkout the repository
          - name: Checkout
            uses: actions/checkout@v4
            with:
              ref: ${{ github.event.pull_request.head.ref }}
            
            # build the Bicep file and output the ARM template
          - name: Bicep Build and Lint
            run: |
              bicep build main.bicep --outdir ARM              

            # push branch commit and push the ./ARM/main.json file to the branch that triggered the workflow
          - name: Commit ARM Template
            run: |
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git config --global user.name "github-actions[bot]"
              git add ARM/main.json
              git commit -m "ARM Template Build-${{ github.run_id }}"
              git status
              git push origin HEAD:${{ github.event.pull_request.head.ref }}
              

                