name: "LabBuilder - Deploy AVNM Scenarios"

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:
    inputs:
      LabBuilderLocation:
        type: choice
        options:
          - swedencentral
        required: true
        default: swedencentral
      LabBuilderCleanup:
        type: boolean
        required: true
        default: true

jobs:
    Deploy:
        uses: ./.github/workflows/deploy.yml
        with:
            LabBuilderType: avnm
            LabBuilderCleanup: ${{ inputs.LabBuilderCleanup }}
            LabBuilderLocation: ${{ inputs.LabBuilderLocation }}
        secrets:
            inherit
