name: "LabBuilder - Deploy AVNM Scenarios"

on:
  workflow_dispatch:
    inputs:
      MultiOrSingleRegion:
        description: "Deploy Multi or Single Region?"
        type: choice
        options:
          - MultiRegion
          - SingleRegion        
        default: SingleRegion
        required: true
      DeploymentLocation:
        description: "Location of the deployment"
        type: choice
        options:
          - northeurope
          - westeurope
          - swedencentral
          - germanywestcentral
        required: true
        default: swedencentral
      Cleanup:
        description: "Cleanup the deployment?"
        type: boolean
        required: true
        default: true
      OnlyValidate:
        description: "Only validate the deployment?"
        type: boolean
        required: true
        default: false
        
jobs:
    Deploy:
        uses: ./.github/workflows/deploy.yml
        with:
            MultiOrSingleRegion: ${{ inputs.MultiOrSingleRegion }}
            DeploymentLocation: ${{ inputs.DeploymentLocation }}
            Type: 'avnm'
            Cleanup: ${{ inputs.Cleanup }}            
            OnlyValidate: ${{ inputs.OnlyValidate }}
        secrets:
            inherit
