name: "LabBuilder - CleanUp"

on:
  workflow_dispatch:
    inputs:
      Type:
        description: "Type to deploy"
        type: choice
        options:
          - vnet
          - vwan
          - avnm
        required: true
        default: vwan
  workflow_call:
    inputs:
      Type:
        type: string
        required: true

permissions:
  id-token: write
    
jobs:    
  removeResources:
    name: "Remove LabBuilder resources"
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Cleanup
        shell: pwsh
        run: |
          Write-Host "List of Resource groups to be deleted...."
          $resourceGroups = Get-AzResourceGroup -Tag @{ LabBuilder = "Validation"; LabBuilderType = "${{ inputs.Type }}" }
          $resourceGroups | Format-Table ResourceGroupName, Location

          if ($resourceGroups.Count -eq 0) {
            Write-Host "No resource groups found to delete."
            exit 0
          } else {
            Write-Host "Found $($resourceGroups.Count) resource groups to delete."
            Write-Host "Removing Resource groups..."
            foreach ($rg in $resourceGroups) {
              Remove-AzResourceGroup -Name $rg.ResourceGroupName -Force -AsJob
            }
          }

          
