name: "LabBuilder - CleanUp"

on:
  workflow_dispatch:
    inputs:
      Type:
        description: "Type to deploy"
        type: choice
        options:
          - vnet
          - vwan
          - avnm
        required: true
        default: vwan
  workflow_call:
    inputs:
      Type:
        type: string
        required: true

permissions:
  id-token: write
    
jobs:
  GetSubscriptionIDs:
    name: "Gather Subscription IDs"
    runs-on: ubuntu-latest
    steps:
      - name: Get Subscription IDs
        shell: pwsh
        run: |
          Write-Host "--------------------------------"
          $subIDs = "${{ secrets.LOCATIONS }}"
          Write-Host "Subscription IDs to be cleaned up: $subIDs"
          Write-Host "Type to be cleaned up: ${{ inputs.Type }}"
          Write-Host "--------------------------------"

  # removeResources:
  #   name: "Remove ${{ inputs.Type }} resources, Sub${{ strategy.job-index }}"
  #   needs: GetSubscriptionIDs
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       sub_id: ${{ fromJson(inputs.subscriptionIDs) }}
  #   steps:
  #     - name: Review values
  #       run: |
  #         echo "Subscription ID to be cleaned up: ${{ matrix.sub_id }}"

  #     - name: Azure Login
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ matrix.sub_id }}
  #     - name: Cleanup ${{ matrix.sub_id }}
  #       run: |
  #         echo "Switching to subscription ${{ matrix.sub_id }} ..."
  #         az account set --subscription ${{ matrix.sub_id }}
  #         echo 'List of Resource groups to be deleted....'
  #         az group list --tag LabBuilder=Validation --tag LabBuilderType=${{ inputs.Type }} --output table
  #         echo 'Removing Resource groups...'
  #         az group list --tag LabBuilder=Validation --tag LabBuilderType=${{ inputs.Type }} --query "[].[name]" --output tsv | xargs -r -l az group delete --yes --no-wait --name
