name: "LabBuilder - CleanUp"

on:
  workflow_dispatch:
    inputs:
      LabBuilderType:
        type: choice
        options:
          - vnet
          - vwan
        required: true
        default: vnet
  workflow_call:
    inputs:
      LabBuilderType:
        type: string
        required: true

permissions:
  id-token: write
  
jobs:
  VNETremoval:
    name: "Remove deployments"
    runs-on: ubuntu-latest
    # environment: LabBuilderCleanup
    strategy:
      matrix:
        subscription: [hub,spoke,onprem]
        include:
          - subscription: hub
            subscription_id: AZURE_SUBSCRIPTION_ID
          - subscription: spoke
            subscription_id: AZURE_SUBSCRIPTION_ID
          - subscription: onprem
            subscription_id: AZURE_SUBSCRIPTION_ID

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Cleanup ${{ matrix.subscription }} Subsription
        run: |
          echo 'Switching to ${{ matrix.subscription }} Subscription...'
          az account set --subscription ${{ secrets[matrix.subscription_id] }}
          echo 'List of Resource groups to be deleted....'
          az group list --tag LabBuilder=Validation --tag LabBuilderType=${{ inputs.LabBuilderType }} --output table
          echo 'Removing Resource groups...'
          az group list --tag LabBuilder=Validation --tag LabBuilderType=${{ inputs.LabBuilderType }} --query "[].[name]" --output tsv | xargs -r -l az group delete --yes --no-wait --name
