name: "LabBuilder - CleanUp"

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      LabBuilderType:
        type: choice
        options:
          - vnet
          - vwan
        required: true
        default: vnet
  workflow_call:
    inputs:
      LabBuilderType:
        type: string
        required: true

jobs:
  VNETremoval:
    name: "Remove deployments"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subscription: [hub,spoke,onprem]
        include:
          - subscription: hub
            subscription_id: HUB_SUBSCRIPTION_ID
          - subscription: spoke
            subscription_id: SPOKE_SUBSCRIPTION_ID
          - subscription: onprem
            subscription_id: ONPREM_SUBSCRIPTION_ID

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Cleanup ${{ matrix.subscription }} Subsription
        run: |
          echo 'Switching to ${{ matrix.subscription }} Subscription...'
          az account set --subscription ${{ secrets[matrix.subscription_id] }}
          echo 'List of Resource groups to be deleted....'
          az group list --tag LabBuilder=Validation --tag LabBuilderType=${{ inputs.LabBuilderType }} --output table
          echo 'Removing Resource groups...'
          az group list --tag LabBuilder=Validation --tag LabBuilderType=${{ inputs.LabBuilderType }} --query "[].[name]" --output tsv | xargs -r -l az group delete --yes --no-wait --name
