name: "LabBuilder - CleanUp"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
    
jobs:    
  removeResources:
    name: "Remove LabBuilder resources"
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        id: login
        uses: azure/login@v2
        with:
          enable-AzPSSession: true
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Cleanup
        uses: azure/powershell@v2
        with:
          azPSVersion: 'latest'
          inlineScript: |
            Write-Host "Searching for resource groups tagged with LabBuilder=validation..."
            $resourceGroups = Get-AzResourceGroup -Tag @{ LabBuilder = "validation" }

            if (-not $resourceGroups) {
              Write-Host "No resource groups found to delete. Exiting."
              exit 0
            }

            Write-Host "Found $($resourceGroups.Count) resource group(s) to delete:"
            $resourceGroups | Select-Object ResourceGroupName, Location, Tags | Format-Table -AutoSize

            $jobs = @()
            foreach ($rg in $resourceGroups) {
              Write-Host "Starting deletion job for resource group: $($rg.ResourceGroupName)..."
              $jobs += Start-Job -ScriptBlock {
                param($rgName)
                Import-Module Az.Resources
                Write-Host "Deleting resource group: $rgName..."
                Remove-AzResourceGroup -Name $rgName -Force -ErrorAction Stop
                Write-Host "Deleted: $rgName"
              } -ArgumentList $rg.ResourceGroupName
            }

            Write-Host "Waiting for all deletion jobs to complete..."
            $jobs | ForEach-Object { 
              Receive-Job -Job $_ -Wait -AutoRemoveJob 
            }
            Write-Host "All resource groups deleted."

          
