name: "LabBuilder - CleanUp"

on:
  workflow_dispatch:
    inputs:
      MultiOrSingleRegion:
        description: "Deploy Multi or Single Region?"
        type: choice
        options:
          - MultiRegion
          - SingleRegion        
        default: SingleRegion
        required: true
      Type:
        description: "Type of LabBuilder deployment"
        type: choice
        options:
          - vnet
          - vwan
          - avnm
        required: true
        default: vnet
  workflow_call:
    inputs:
      MultiOrSingleRegion:
        type: string
        required: true
      Type:
        type: string
        required: true

permissions:
  id-token: write
  
jobs:
  prepare-matrix:
    environment:
      name: ${{ inputs.MultiOrSingleRegion }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.buildMatrix.outputs.matrix }}
    steps:
      - name: "prep metrix json"
        id: buildMatrix
        run: |
          json_input='${{ secrets.LOCATIONS }}'
          if [ -z "$json_input" ]; then
            echo "Error: LOCATIONS secret is empty or not set."
            exit 1
          fi
          unique=$(echo "$json_input" | jq -c '[.[].hubSubscriptionID, .[].spokeSubscriptionID, .[].onPremSubscriptionID] | unique | map({sub_id: .})]')
          if [ -z "$unique" ]; then
            echo "Error: Failed to generate unique subscription IDs."
            exit 1
          fi
          echo "matrix=$(echo "{\"include\":$unique}" | jq -c)" >> "$GITHUB_OUTPUT"

      - name: display-output
        run: |
          echo "Matrix output:"
          echo "${{ steps.buildMatrix.outputs.matrix }}"
          echo "Matrix output fromJson:"
          echo "${{ fromJson(steps.buildMatrix.outputs.matrix) }}"

  reviewValues:
    name: "Review values"
    runs-on: ubuntu-latest
    needs: prepare-matrix
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Review values
        run: |
          echo "Subscription ID to be cleaned up:"
          echo "${{ matrix.sub_id }}"
          echo "LabBuilder Type:"
          echo "${{ inputs.Type }}"
