name: "LabBuilder - Deploy Scenarios"

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:
    inputs:
      LabBuilderType:
        type: choice
        options:
          - vnet
          - vwan
        required: true
        default: vwan
      LabBuilderCleanup:
        type: boolean
        required: true
        default: true
  workflow_call:
    inputs:
      LabBuilderType:
        type: string
        required: true
      LabBuilderCleanup:
        type: boolean
        required: true

jobs:
  BicepBuildandLint:
    name: "Bicep Build and Lint"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bicep Build and Lint
        run: |
          az bicep install
          az bicep version
          az bicep build --file main.bicep

  DeployScenarios:
    name: "Deploy ${{ inputs.LabBuilderType }} scenarios"
    runs-on: ubuntu-latest
    needs: BicepBuildandLint
    strategy:
      max-parallel: 1
      matrix:
        scenarios:
          [
            "scenario1.${{ inputs.LabBuilderType }}.parameters.json"
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Validating scenario ${{ inputs.LabBuilderType }}"
        uses: Azure/arm-deploy@v1
        with:
          scope: "subscription"
          subscriptionId: ${{ secrets.HUB_SUBSCRIPTION_ID }}
          region: westus3
          template: main.bicep
          parameters: "ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }} sharedKey=${{ secrets.SHAREDKEY }} hubSubscriptionID=${{ secrets.HUB_SUBSCRIPTION_ID }} spokeSubscriptionID=${{ secrets.SPOKE_SUBSCRIPTION_ID }} onPremSubscriptionID=${{ secrets.ONPREM_SUBSCRIPTION_ID }}"
          deploymentMode: "validate"
          deploymentName: "LabBuilderValidation-${{ inputs.LabBuilderType }}"
      - name: "Deploy scenario ${{ inputs.LabBuilderType }}"
        uses: Azure/arm-deploy@v1
        with:
          scope: "subscription"
          subscriptionId: ${{ secrets.HUB_SUBSCRIPTION_ID }}
          region: westus3
          template: main.bicep
          parameters: "ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }} sharedKey=${{ secrets.SHAREDKEY }} hubSubscriptionID=${{ secrets.HUB_SUBSCRIPTION_ID }} spokeSubscriptionID=${{ secrets.SPOKE_SUBSCRIPTION_ID }} onPremSubscriptionID=${{ secrets.ONPREM_SUBSCRIPTION_ID }}"
          deploymentName: "LabBuilderValidation-${{ inputs.LabBuilderType }}"



        
