name: 'LabBuilder - Lint, Validation and Deploy Scenarios'

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:

jobs:
  lint:
    name: 'Bicep Build (Lint)'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Bicep Build
        run: |
          az bicep install
          az bicep version
          az bicep build --file main.bicep

  VNETdeployments:
    name: 'VNET Scenarios'
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 1
      matrix:
        scenarios: [scenario1.vnet.parameters.json,scenario2.vnet.parameters.json]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Validation'
        uses: Azure/arm-deploy@v1.0.8
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.VNET_SUBSCRIPTION }}
          region: WestEurope
          template: main.bicep
          parameters: 'ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}'
          deploymentMode: 'validate'
          deploymentName: 'LabBuilderValidation'
      - name: 'Deployment'
        uses: Azure/arm-deploy@v1.0.8
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.VNET_SUBSCRIPTION }}
          region: WestEurope
          template: main.bicep
          parameters: 'ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}'
          deploymentName: 'LabBuilderValidation-Deployment'

  VNETremoval:
    name: 'Remove VNET deployment'
    runs-on: ubuntu-latest
    needs: VNETdeployments
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  VWANdeployments:
    name: 'VWAN Scenarios'
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 1
      matrix:
        scenarios: []

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Validation'
        uses: Azure/arm-deploy@v1.0.8
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.VWAN_SUBSCRIPTION }}
          region: WestEurope
          template: main.bicep
          parameters: 'ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}'
          deploymentMode: 'validate'
          deploymentName: 'LabBuilderValidation'
      - name: 'Deployment'
        uses: Azure/arm-deploy@v1.0.8
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.VWAN_SUBSCRIPTION }}
          region: WestEurope
          template: main.bicep
          parameters: 'ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}'
          deploymentName: 'LabBuilderValidation-Deployment'

  VWANremoval:
    name: 'Remove VWAN deployment'
    runs-on: ubuntu-latest
    needs: VWANdeployments
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}