name: 'Bicep Test and Validation'

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Bicep Build
        run: |
          az bicep install
          az bicep version
          az bicep build --file main.bicep

  deployments:
    name: 'Validate & Deploy'
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 1
      matrix:
        scenarios: [scenario1.vnet.parameters.json]
        mode: [Validate,Incremental]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Azure Deploy ${{ matrix.mode }}'
        uses: Azure/arm-deploy@v1.0.8
        with:
          scope: 'subscription'
          subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionid }}
          region: WestEurope
          template: main.bicep
          parameters: 'ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}'
          deploymentMode: ${{ matrix.mode }}
          deploymentName: 'LabBuilder-${{ matrix.mode }}'
          additionalArguments: '--verbose'
         
