name: "LabBuilder - Deploy VNET Scenarios"

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:

jobs:
    Deploy:
        uses: ./.github/workflows/deploy.yml
        with:
            LabBuilderType: vnet
            LabBuilderCleanup: true
        secrets:
            inherit
