name: "LabBuilder - Deploy VNET Scenarios"

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:
    inputs:
      LabBuilderLocation:
        type: choice
        options:
          - swedencentral
        required: true
        default: swedencentral
      LabBuilderCleanup:
        type: boolean
        required: true
        default: true
      OnlyValidate:
        type: boolean
        required: true
        default: false

jobs:
    Deploy:
        uses: ./.github/workflows/deploy.yml
        with:
            LabBuilderType: vnet
            LabBuilderCleanup: ${{ inputs.LabBuilderCleanup }}
            LabBuilderLocation: ${{ inputs.LabBuilderLocation }}
            OnlyValidate: ${{ inputs.OnlyValidate }}
        secrets:
            inherit
