name: "LabBuilder - Deploy VNET Scenarios"

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:
    inputs:
      LabBuilderCleanup:
        type: boolean
        required: true
        default: true

jobs:
    Deploy:
        uses: ./.github/workflows/deploy.yml
        with:
            LabBuilderType: vnet
            LabBuilderCleanup: ${{ inputs.LabBuilderCleanup }}
        secrets:
            inherit
