name: "VWAN - Lint, Validation and Deploy Scenarios"

on:
  push:
    branches: none
  pull_request:
    branches: none
  workflow_dispatch:

jobs:
  lint:
    name: "Bicep Build (Lint)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Bicep Build
        run: |
          az bicep install
          az bicep version
          az bicep build --file main.bicep

  VWANdeployments:
    name: "VWAN Scenarios"
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 1
      matrix:
        scenarios:
          [
            scenario1.vwan.parameters.json,
            scenario2.vwan.parameters.json,
            scenario3.vwan.parameters.json,
            scenario4.vwan.parameters.json,
            scenario5.vwan.parameters.json,
            scenario6.vwan.parameters.json,
            scenario7.vwan.parameters.json
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Validation"
        uses: Azure/arm-deploy@v1
        with:
          scope: "subscription"
          subscriptionId: ${{ secrets.HUB_SUBSCRIPTION_ID }}
          region: westus3
          template: main.bicep
          parameters: "ARM/params/${{ matrix.scenarios }} adminUsername= ${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }} sharedKey=${{ secrets.SHAREDKEY }} hubSubscriptionID=${{ secrets.HUB_SUBSCRIPTION_ID }} spokeSubscriptionID=${{ secrets.SPOKE_SUBSCRIPTION_ID }} onPremSubscriptionID=${{ secrets.ONPREM_SUBSCRIPTION_ID }}"
          deploymentMode: "validate"
          deploymentName: "LabBuilderValidation-VWAN"
      - name: "Deployment"
        uses: Azure/arm-deploy@v1
        with:
          scope: "subscription"
          subscriptionId: ${{ secrets.HUB_SUBSCRIPTION_ID }}
          region: westus3
          template: main.bicep
          parameters: "ARM/params/${{ matrix.scenarios }} adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }} sharedKey=${{ secrets.SHAREDKEY }} hubSubscriptionID=${{ secrets.HUB_SUBSCRIPTION_ID }} spokeSubscriptionID=${{ secrets.SPOKE_SUBSCRIPTION_ID }} onPremSubscriptionID=${{ secrets.ONPREM_SUBSCRIPTION_ID }}"
          deploymentName: "LabBuilderValidation-VWAN"
