name: "LabBuilder - wait for vWAN"

on:
    workflow_dispatch:
    workflow_call:

permissions:
  id-token: write

jobs:
    waitForVWAN:
        name: "check vWAN status"
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                HubIds: [ 'Hub1', 'Hub2' ]
        steps:
            - name: test
              id: test
              run: |
                echo "checking...: ${{ matrix.HubIds }}"

